Repository Sparta-CareNest/carnest-backend, pull requests merged in 2025-04, with the labels that each got.

#15 Feature/common/init
  common/src/main/java/com/carenest/business/common/entity/BaseEntity.java
  common/src/main/java/com/carenest/business/common/exception/BaseErrorCode.java
  common/src/main/java/com/carenest/business/common/exception/BaseException.java
  common/src/main/java/com/carenest/business/common/exception/CommonErrorCode.java
  common/src/main/java/com/carenest/business/common/exception/GlobalExceptionHandler.java
  common/src/main/java/com/carenest/common/response/ApiResponse.java
Labels: chore 🧲

#6 Feature/matching service/init
  build.gradle
  caregiver-service/build.gradle
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/CaregiverServiceApplication.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/config/PageableConfig.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/config/QueryDslConfig.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/domain/model/Caregiver.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/domain/model/GenderType.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/domain/model/category/CaregiverCategoryLocation.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/domain/model/category/CaregiverCategoryService.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/domain/model/category/CategoryLocation.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/domain/model/category/CategoryService.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/domain/repository/CaregiverCustomRepository.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/domain/repository/CaregiverRepository.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/infrastructure/repository/CaregiverRepositoryImpl.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/infrastructure/repository/JpaCaregiverRepository.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/util/PageableUtils.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/util/QueryDslUtils.java
  caregiver-service/src/main/resources/application.yml
  caregiver-service/src/test/java/com/carenest/business/caregiverservice/CaregiverServiceApplicationTests.java
  matching-service/src/main/resources/application.properties
  settings.gradle
Labels: chore 🧲

#17 Feature/reservation/init
  reservation-service/src/main/java/com/carenest/business/reservationservice/application/service/ReservationService.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/application/service/ReservationServiceImpl.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/domain/model/Gender.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/domain/model/Reservation.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/domain/model/ReservationHistory.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/domain/model/ReservationStatus.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/domain/model/ServiceType.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/domain/repository/ReservationRepository.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/domain/repository/ReservationRepositoryImpl.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/domain/service/ReservationDomainService.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/domain/service/ReservationDomainServiceImpl.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/presentation/controller/ReservationController.java
Labels: feat📌

#18 Feature/payment/init
  build.gradle
  payment-service/build.gradle
  payment-service/src/main/java/com/carenest/business/paymentservice/PaymentServiceApplication.java
  payment-service/src/main/java/com/carenest/business/paymentservice/application/service/PaymentService.java
  payment-service/src/main/java/com/carenest/business/paymentservice/application/service/PaymentServiceImpl.java
  payment-service/src/main/java/com/carenest/business/paymentservice/domain/model/Payment.java
  payment-service/src/main/java/com/carenest/business/paymentservice/domain/model/PaymentHistory.java
  payment-service/src/main/java/com/carenest/business/paymentservice/domain/model/PaymentStatus.java
  payment-service/src/main/java/com/carenest/business/paymentservice/domain/service/PaymentDomainService.java
  payment-service/src/main/java/com/carenest/business/paymentservice/domain/service/PaymentDomainServiceImpl.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/repository/PayRepositoryImpl.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/repository/PaymentRepository.java
  payment-service/src/main/java/com/carenest/business/paymentservice/presentation/controller/PaymentController.java
  payment-service/src/main/resources/application.properties
  payment-service/src/test/java/com/carenest/business/paymentservice/PaymentServiceApplicationTests.java
  settings.gradle
Labels: feat📌

#21 Feature/review/init/#13
  build.gradle
  review-service/build.gradle
  review-service/src/main/java/com/carenest/business/reviewservice/ReviewServiceApplication.java
  review-service/src/main/java/com/carenest/business/reviewservice/domain/model/Review.java
  review-service/src/main/resources/application.yml
  review-service/src/test/java/com/carenest/business/reviewservice/ReviewServiceApplicationTests.java
  settings.gradle
Labels: chore 🧲

#25 Feature/caregiver/crud
  caregiver-service/build.gradle
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/CaregiverServiceApplication.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/dto/mapper/CaregiverApplicationMapper.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/dto/request/CaregiverCreateRequestServiceDTO.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/dto/response/CaregiverCreateResponseServiceDTO.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/dto/response/CaregiverReadResponseServiceDTO.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/dto/response/CaregiverUpdateResponseServiceDTO.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/service/CaregiverService.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/domain/model/Caregiver.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/domain/model/category/CategoryService.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/domain/repository/CaregiverCustomRepository.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/domain/repository/CaregiverRepository.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/domain/repository/CategoryLocationRepository.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/domain/repository/CategoryServiceRepository.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/exception/CaregiverException.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/exception/ErrorCode.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/exception/GlobalExceptionHandler.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/infrastructure/repository/CaregiverCustomRepository.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/infrastructure/repository/CaregiverRepositoryImpl.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/infrastructure/repository/JpaCaregiverRepository.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/presentation/controller/CaregiverController.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/presentation/dto/mapper/CaregiverPresentationMapper.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/presentation/dto/request/CaregiverCreateRequestDTO.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/presentation/dto/request/CaregiverUpdateRequestDTO.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/presentation/dto/response/CaregiverCreateResponseDTO.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/presentation/dto/response/CaregiverReadResponseDTO.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/presentation/dto/response/CaregiverUpdateResponseDTO.java
  caregiver-service/src/test/java/com/carenest/business/caregiverservice/CaregiverServiceApplicationTests.java
  common/src/main/java/com/carenest/business/common/entity/BaseEntity.java
Labels: feat📌

#27 Feature/reservation/crud
  reservation-service/build.gradle
  reservation-service/src/main/java/com/carenest/business/reservationservice/application/dto/request/ReservationCreateRequest.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/application/dto/request/ReservationUpdateRequest.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/application/dto/response/ReservationResponse.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/application/service/ReservationService.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/application/service/ReservationServiceImpl.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/domain/model/Reservation.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/domain/repository/ReservationHistoryRepository.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/domain/repository/ReservationRepository.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/domain/repository/ReservationRepositoryImpl.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/domain/service/ReservationDomainService.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/domain/service/ReservationDomainServiceImpl.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/exception/CannotCancelReservationException.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/exception/CannotRejectReservationException.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/exception/DuplicateReservationException.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/exception/InvalidReservationStatusException.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/exception/InvalidReservationTimeException.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/exception/ReservationErrorCode.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/exception/ReservationException.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/exception/ReservationNotFoundException.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/exception/UnauthorizedReservationAccessException.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/presentation/controller/ReservationController.java
  reservation-service/src/main/resources/application.properties
  reservation-service/src/main/resources/application.yml
Labels: feat📌

#28 Feature/payment/crud
  payment-service/src/main/java/com/carenest/business/paymentservice/application/dto/request/PaymentCompleteRequest.java
  payment-service/src/main/java/com/carenest/business/paymentservice/application/dto/request/PaymentCreateRequest.java
  payment-service/src/main/java/com/carenest/business/paymentservice/application/dto/request/RefundRequest.java
  payment-service/src/main/java/com/carenest/business/paymentservice/application/dto/response/PaymentResponse.java
  payment-service/src/main/java/com/carenest/business/paymentservice/application/service/PaymentService.java
  payment-service/src/main/java/com/carenest/business/paymentservice/application/service/PaymentServiceImpl.java
  payment-service/src/main/java/com/carenest/business/paymentservice/domain/service/PaymentDomainService.java
  payment-service/src/main/java/com/carenest/business/paymentservice/domain/service/PaymentDomainServiceImpl.java
  payment-service/src/main/java/com/carenest/business/paymentservice/exception/InvalidPaymentStatusException.java
  payment-service/src/main/java/com/carenest/business/paymentservice/exception/PaymentErrorCode.java
  payment-service/src/main/java/com/carenest/business/paymentservice/exception/PaymentException.java
  payment-service/src/main/java/com/carenest/business/paymentservice/exception/PaymentNotFoundException.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/repository/PayRepositoryImpl.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/repository/PaymentHistoryRepository.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/repository/PaymentRepository.java
  payment-service/src/main/java/com/carenest/business/paymentservice/presentation/controller/PaymentController.java
  payment-service/src/main/resources/application.properties
  payment-service/src/main/resources/application.yml
Labels: feat📌

#32 Feature/Review/CRUD
  review-service/src/main/java/com/carenest/business/reviewservice/ReviewServiceApplication.java
  review-service/src/main/java/com/carenest/business/reviewservice/application/dto/request/ReviewCreateRequestDto.java
  review-service/src/main/java/com/carenest/business/reviewservice/application/dto/request/ReviewUpdateRequestDto.java
  review-service/src/main/java/com/carenest/business/reviewservice/application/dto/response/ReviewCreateResponseDto.java
  review-service/src/main/java/com/carenest/business/reviewservice/application/dto/response/ReviewUpdateResponseDto.java
  review-service/src/main/java/com/carenest/business/reviewservice/application/service/ReviewService.java
  review-service/src/main/java/com/carenest/business/reviewservice/domain/model/Review.java
  review-service/src/main/java/com/carenest/business/reviewservice/domain/repository/ReviewRepository.java
  review-service/src/main/java/com/carenest/business/reviewservice/infrastructure/repository/JpaReviewRepository.java
  review-service/src/main/java/com/carenest/business/reviewservice/presentation/controller/ReviewController.java
Labels: feat📌

#36 Feature/caregiver/search
  caregiver-service/build.gradle
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/dto/response/CaregiverSearchResponseServiceDTO.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/service/CaregiverService.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/service/CaregiverServiceImpl.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/domain/model/Caregiver.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/infrastructure/repository/CaregiverRepository.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/infrastructure/repository/querydsl/CaregiverCustomRepository.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/infrastructure/repository/querydsl/CaregiverRepositoryImpl.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/presentation/controller/CaregiverController.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/presentation/dto/mapper/CaregiverPresentationMapper.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/presentation/dto/response/CaregiverSearchResponseDTO.java
Labels: bug 🐞, feat📌

#41 Feature/reservation/search
  reservation-service/build.gradle
  reservation-service/src/main/java/com/carenest/business/reservationservice/application/dto/request/PaymentLinkRequest.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/application/dto/request/ReservationAcceptRequest.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/application/dto/request/ReservationCancelRequest.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/application/dto/request/ReservationRejectRequest.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/application/dto/request/ReservationSearchRequest.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/application/service/ReservationService.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/application/service/ReservationServiceImpl.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/domain/repository/ReservationRepository.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/domain/repository/ReservationRepositoryCustom.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/domain/repository/ReservationRepositoryCustomImpl.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/exception/PaymentAlreadyProcessedException.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/presentation/controller/ReservationController.java
  reservation-service/src/main/resources/application.yml
Labels: feat📌

#42 Feature/payment/crud
  payment-service/src/main/java/com/carenest/business/paymentservice/application/dto/request/RefundRequest.java
  payment-service/src/main/java/com/carenest/business/paymentservice/application/dto/response/PaymentHistoryDetailResponse.java
  payment-service/src/main/java/com/carenest/business/paymentservice/application/dto/response/PaymentHistoryResponse.java
  payment-service/src/main/java/com/carenest/business/paymentservice/application/dto/response/PaymentListResponse.java
  payment-service/src/main/java/com/carenest/business/paymentservice/application/dto/response/PaymentResponse.java
  payment-service/src/main/java/com/carenest/business/paymentservice/application/service/PaymentService.java
  payment-service/src/main/java/com/carenest/business/paymentservice/application/service/PaymentServiceImpl.java
  payment-service/src/main/java/com/carenest/business/paymentservice/domain/model/Payment.java
  payment-service/src/main/java/com/carenest/business/paymentservice/exception/DuplicatePaymentException.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/external/PaymentGatewayService.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/external/PaymentGatewayServiceImpl.java
  payment-service/src/main/java/com/carenest/business/paymentservice/presentation/controller/PaymentController.java
  payment-service/src/main/resources/application.yml
Labels: feat📌

#38 Feature/chat service init
  chat-service/src/main/java/com/carenest/business/chatservice/domain/model/ChatMessage.java
  chat-service/src/main/java/com/carenest/business/chatservice/domain/model/ChatRoom.java
  notification-service/src/main/resources/application.yml
  settings.gradle
Labels: feat📌, chore 🧲

#37 Feature/user/auth
  user-service/build.gradle
  user-service/src/main/java/com/carenest/business/userservice/application/dto/request/LoginRequestDTO.java
  user-service/src/main/java/com/carenest/business/userservice/application/dto/request/SignupRequestDTO.java
  user-service/src/main/java/com/carenest/business/userservice/application/dto/response/LoginResponseDTO.java
  user-service/src/main/java/com/carenest/business/userservice/application/dto/response/SignupResponseDTO.java
  user-service/src/main/java/com/carenest/business/userservice/application/service/UserService.java
  user-service/src/main/java/com/carenest/business/userservice/domain/model/User.java
  user-service/src/main/java/com/carenest/business/userservice/domain/model/UserRoleEnum.java
  user-service/src/main/java/com/carenest/business/userservice/domain/repository/UserRepository.java
  user-service/src/main/java/com/carenest/business/userservice/infrastructure/configuration/SecurityConfig.java
  user-service/src/main/java/com/carenest/business/userservice/infrastructure/security/JwtUtil.java
  user-service/src/main/java/com/carenest/business/userservice/presentation/controller/UserController.java
  user-service/src/main/resources/application.yml
Labels: feat📌

#43 Feature/Review search 기능, exception 처리
  review-service/build.gradle
  review-service/src/main/java/com/carenest/business/reviewservice/application/dto/request/ReviewSearchRequestDto.java
  review-service/src/main/java/com/carenest/business/reviewservice/application/dto/response/ReviewSearchResponseDto.java
  review-service/src/main/java/com/carenest/business/reviewservice/application/service/ReviewService.java
  review-service/src/main/java/com/carenest/business/reviewservice/config/QueryDslConfig.java
  review-service/src/main/java/com/carenest/business/reviewservice/domain/repository/ReviewRepositoryCustom.java
  review-service/src/main/java/com/carenest/business/reviewservice/exception/ErrorCode.java
  review-service/src/main/java/com/carenest/business/reviewservice/exception/GlobalExceptionHandler.java
  review-service/src/main/java/com/carenest/business/reviewservice/exception/ReviewException.java
  review-service/src/main/java/com/carenest/business/reviewservice/infrastructure/repository/ReviewRepositoryImpl.java
  review-service/src/main/java/com/carenest/business/reviewservice/presentation/controller/ReviewController.java
  review-service/src/main/resources/application.yml
Labels: feat📌

#46 Feature/caregiver/internal
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/service/CaregiverService.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/service/CaregiverServiceImpl.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/domain/model/Caregiver.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/domain/service/CaregiverDomainService.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/domain/service/CaregiverDomainServiceImpl.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/presentation/controller/CaregiverController.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/presentation/controller/CaregiverInternalController.java
Labels: feat📌, refactor ⚙

#55 Feature/chat service
  chat-service/src/main/java/com/carenest/business/chatservice/application/dto/request/ChatMessageRequestDto.java
  chat-service/src/main/java/com/carenest/business/chatservice/application/dto/request/ChatRoomCreateRequestDto.java
  chat-service/src/main/java/com/carenest/business/chatservice/application/dto/response/ChatMessageResponseDto.java
  chat-service/src/main/java/com/carenest/business/chatservice/application/dto/response/ChatRoomResponseDto.java
  chat-service/src/main/java/com/carenest/business/chatservice/application/service/ChatMessageService.java
  chat-service/src/main/java/com/carenest/business/chatservice/application/service/ChatMessageServiceImpl.java
  chat-service/src/main/java/com/carenest/business/chatservice/application/service/ChatRoomService.java
  chat-service/src/main/java/com/carenest/business/chatservice/application/service/ChatRoomServiceImpl.java
  chat-service/src/main/java/com/carenest/business/chatservice/domain/repository/ChatMessageRepository.java
  chat-service/src/main/java/com/carenest/business/chatservice/domain/repository/ChatRoomRepository.java
  chat-service/src/main/java/com/carenest/business/chatservice/infrastructure/config/WebSocketConfig.java
  chat-service/src/main/java/com/carenest/business/chatservice/presentation/controller/ChatMessageController.java
  chat-service/src/main/java/com/carenest/business/chatservice/presentation/controller/ChatRoomController.java
Labels: feat📌

#57 Feature/notification read api
  notification-service/src/main/java/com/carenest/business/notificationservice/NotificationServiceApplication.java
  notification-service/src/main/java/com/carenest/business/notificationservice/application/service/NotificationService.java
  notification-service/src/main/java/com/carenest/business/notificationservice/application/service/NotificationServiceImpl.java
  notification-service/src/main/java/com/carenest/business/notificationservice/domain/model/Notification.java
  notification-service/src/main/java/com/carenest/business/notificationservice/presentation/controller/NotificationController.java
Labels: feat📌

#51 Feature/caregiver/s3
  caregiver-service/build.gradle
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/dto/request/CaregiverCreateRequestServiceDTO.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/service/CaregiverService.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/service/CaregiverServiceImpl.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/config/AmazonConfig.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/domain/model/Caregiver.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/domain/service/CaregiverDomainService.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/domain/service/CaregiverDomainServiceImpl.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/exception/ErrorCode.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/infrastructure/repository/UuidRepository.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/infrastructure/s3/AmazonS3Manager.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/infrastructure/s3/MultipartJackson2HttpMessageConverter.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/infrastructure/s3/Uuid.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/presentation/controller/CaregiverController.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/presentation/dto/request/CaregiverCreateRequestDTO.java
  caregiver-service/src/main/resources/application.yml
Labels: feat📌, refactor ⚙

#53 refactor: 결제 컨트롤러 ResponseEntity 제거
  payment-service/src/main/java/com/carenest/business/paymentservice/presentation/controller/PaymentController.java
Labels: refactor ⚙

#52 Feature/refactor reservation
  common/src/main/java/com/carenest/business/common/model/UserRole.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/application/dto/request/ReservationCreateRequest.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/application/dto/response/ReservationResponse.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/application/service/ReservationService.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/application/service/ReservationServiceImpl.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/domain/model/PaymentStatus.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/domain/model/Reservation.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/domain/model/ReservationHistory.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/domain/service/ReservationDomainService.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/domain/service/ReservationDomainServiceImpl.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/presentation/controller/ReservationController.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/presentation/dto/mapper/ReservationMapper.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/presentation/dto/response/ReservationResponse.java
Labels: refactor ⚙

#66 Feature/Review/average rating
  review-service/src/main/java/com/carenest/business/reviewservice/ReviewServiceApplication.java
  review-service/src/main/java/com/carenest/business/reviewservice/application/dto/response/CaregiverRatingDto.java
  review-service/src/main/java/com/carenest/business/reviewservice/application/dto/response/CaregiverTopRatingDto.java
  review-service/src/main/java/com/carenest/business/reviewservice/application/service/ReviewService.java
  review-service/src/main/java/com/carenest/business/reviewservice/domain/repository/ReviewRepository.java
  review-service/src/main/java/com/carenest/business/reviewservice/exception/ErrorCode.java
  review-service/src/main/java/com/carenest/business/reviewservice/infrastructure/client/CaregiverInternalClient.java
  review-service/src/main/java/com/carenest/business/reviewservice/presentation/controller/ReviewController.java
Labels: feat📌

#67 Feature/caregiver/api
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/service/CaregiverService.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/service/CaregiverServiceImpl.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/infrastructure/repository/querydsl/CaregiverCustomRepository.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/infrastructure/repository/querydsl/CaregiverRepositoryImpl.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/presentation/controller/CaregiverInternalController.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/presentation/dto/mapper/CaregiverPresentationMapper.java
Labels: feat📌

#63 Feature/user/crud
  common/src/main/java/com/carenest/business/common/annotation/AuthUser.java
  common/src/main/java/com/carenest/business/common/annotation/AuthUserArgumentResolver.java
  common/src/main/java/com/carenest/business/common/annotation/AuthUserInfo.java
  gateway-service/build.gradle
  gateway-service/src/main/java/com/carenest/business/gatewayservice/GatewayConfig.java
  gateway-service/src/main/java/com/carenest/business/gatewayservice/JwtAuthFilter.java
  gateway-service/src/main/java/com/carenest/business/gatewayservice/JwtUtil.java
  user-service/build.gradle
  user-service/src/main/java/com/carenest/business/userservice/application/dto/request/UpdateUserRequestDTO.java
  user-service/src/main/java/com/carenest/business/userservice/application/dto/response/UpdateUserResponseDTO.java
  user-service/src/main/java/com/carenest/business/userservice/application/dto/response/UserInfoResponseDTO.java
  user-service/src/main/java/com/carenest/business/userservice/application/service/UserService.java
  user-service/src/main/java/com/carenest/business/userservice/domain/model/User.java
  user-service/src/main/java/com/carenest/business/userservice/domain/model/UserRoleEnum.java
  user-service/src/main/java/com/carenest/business/userservice/domain/repository/UserRepository.java
  user-service/src/main/java/com/carenest/business/userservice/infrastructure/configuration/WebConfig.java
  user-service/src/main/java/com/carenest/business/userservice/infrastructure/security/JwtUtil.java
  user-service/src/main/java/com/carenest/business/userservice/presentation/controller/UserController.java
Labels: feat📌

#72 feat: 사용자 ID 검증 API 추가
  user-service/src/main/java/com/carenest/business/userservice/application/service/UserService.java
  user-service/src/main/java/com/carenest/business/userservice/presentation/controller/UserInternalController.java
Labels: feat📌

#73 Feature/reservation/feign client
  reservation-service/build.gradle
  reservation-service/src/main/java/com/carenest/business/reservationservice/application/service/ReservationServiceImpl.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/domain/model/Reservation.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/exception/IntegrationErrorException.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/infrastructure/client/CaregiverServiceClient.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/infrastructure/client/NotificationServiceClient.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/infrastructure/client/PaymentServiceClient.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/infrastructure/client/dto/request/NotificationCreateRequestDto.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/infrastructure/client/dto/request/PaymentCreateRequestDto.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/infrastructure/client/dto/response/CaregiverDetailResponseDto.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/infrastructure/client/dto/response/NotificationResponseDto.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/infrastructure/client/dto/response/PaymentResponseDto.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/infrastructure/config/CircuitBreakerConfig.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/infrastructure/config/FeignClientConfig.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/infrastructure/config/FeignErrorDecoderConfig.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/infrastructure/exception/FeignClientExceptionHandler.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/infrastructure/service/ExternalServiceClient.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/infrastructure/service/ExternalServiceClientImpl.java
Labels: feat📌

#75 Feature/caregiver/user check
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/service/CaregiverService.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/service/CaregiverServiceImpl.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/config/WebConfig.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/infrastructure/client/UserClient.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/infrastructure/repository/CaregiverRepository.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/infrastructure/repository/querydsl/CaregiverCustomRepository.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/infrastructure/repository/querydsl/CaregiverRepositoryImpl.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/presentation/controller/CaregiverController.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/presentation/controller/CaregiverInternalController.java
  gateway-service/build.gradle
  gateway-service/src/main/java/com/carenest/business/gatewayservice/GatewayConfig.java
  gateway-service/src/main/java/com/carenest/business/gatewayservice/JwtAuthFilter.java
Labels: refactor ⚙

#76 Feature/notification feignclient
  gateway-service/src/main/java/com/carenest/business/gatewayservice/GatewayConfig.java
  notification-service/build.gradle
  notification-service/src/main/java/com/carenest/business/notificationservice/NotificationServiceApplication.java
  notification-service/src/main/java/com/carenest/business/notificationservice/application/dto/request/NotificationCreateRequestDto.java
  notification-service/src/main/java/com/carenest/business/notificationservice/application/dto/response/UserInfoResponseDto.java
  notification-service/src/main/java/com/carenest/business/notificationservice/application/service/NotificationServiceImpl.java
  notification-service/src/main/java/com/carenest/business/notificationservice/infrastructure/client/UserClient.java
  notification-service/src/main/java/com/carenest/business/notificationservice/infrastructure/config/WebConfig.java
  notification-service/src/main/resources/application.yml
  notification-service/src/test/java/com/carenest/business/notificationservice/application/service/NotificationServiceImplTest.java
Labels: feat📌

#80 Feature/average rating
  docker-compose.yml
  review-service/build.gradle
  review-service/src/main/java/com/carenest/business/reviewservice/application/service/ReviewService.java
  review-service/src/main/java/com/carenest/business/reviewservice/infrastructure/kafka/CaregiverRatingProducer.java
Labels: feat📌

#82 Feature/Review user check
  gateway-service/src/main/java/com/carenest/business/gatewayservice/GatewayConfig.java
  review-service/src/main/java/com/carenest/business/reviewservice/application/service/ReviewService.java
  review-service/src/main/java/com/carenest/business/reviewservice/config/WebConfig.java
  review-service/src/main/java/com/carenest/business/reviewservice/exception/ErrorCode.java
  review-service/src/main/java/com/carenest/business/reviewservice/infrastructure/client/UserInternalClient.java
  review-service/src/main/java/com/carenest/business/reviewservice/presentation/controller/ReviewController.java
Labels: feat📌

#87 Feature/#83 user role
  user-service/src/main/java/com/carenest/business/userservice/UserServiceApplication.java
  user-service/src/main/java/com/carenest/business/userservice/application/dto/request/SignupRequestDTO.java
  user-service/src/main/java/com/carenest/business/userservice/application/service/UserService.java
  user-service/src/main/java/com/carenest/business/userservice/domain/model/User.java
  user-service/src/main/java/com/carenest/business/userservice/domain/model/UserRoleEnum.java
  user-service/src/main/java/com/carenest/business/userservice/infrastructure/security/JwtUtil.java
Labels: feat📌, fix 🛠

#88 Feature/caregiver/create refactor
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/dto/request/CaregiverCreateRequestServiceDTO.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/service/CaregiverService.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/service/CaregiverServiceImpl.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/domain/service/CaregiverDomainService.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/domain/service/CaregiverDomainServiceImpl.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/presentation/controller/CaregiverController.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/presentation/dto/request/CaregiverCreateRequestDTO.java
  common/src/main/java/com/carenest/business/common/annotation/AuthUserInfo.java
Labels: refactor ⚙

#86 Feature/payment/kafka
  common/src/main/java/com/carenest/business/common/event/BaseEvent.java
  common/src/main/java/com/carenest/business/common/event/payment/PaymentCancelledEvent.java
  common/src/main/java/com/carenest/business/common/event/payment/PaymentCompletedEvent.java
  common/src/main/java/com/carenest/business/common/event/reservation/ReservationCancelledEvent.java
  common/src/main/java/com/carenest/business/common/event/reservation/ReservationStatusChangedEvent.java
  gateway-service/src/main/java/com/carenest/business/gatewayservice/GatewayConfig.java
  payment-service/build.gradle
  payment-service/src/main/java/com/carenest/business/paymentservice/application/dto/request/PaymentCreateRequest.java
  payment-service/src/main/java/com/carenest/business/paymentservice/application/service/PaymentService.java
  payment-service/src/main/java/com/carenest/business/paymentservice/application/service/PaymentServiceImpl.java
  payment-service/src/main/java/com/carenest/business/paymentservice/exception/UnauthorizedPaymentAccessException.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/client/UserInternalClient.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/config/KafkaConfig.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/config/KafkaConsumerConfig.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/config/WebConfig.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/kafka/PaymentEventProducer.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/kafka/ReservationEventConsumer.java
  payment-service/src/main/java/com/carenest/business/paymentservice/presentation/controller/PaymentController.java
  payment-service/src/main/resources/application.yml
  reservation-service/build.gradle
  reservation-service/src/main/java/com/carenest/business/reservationservice/application/dto/request/ReservationCreateRequest.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/application/service/ReservationService.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/application/service/ReservationServiceImpl.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/infrastructure/client/UserInternalClient.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/infrastructure/config/KafkaConfig.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/infrastructure/config/KafkaConsumerConfig.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/infrastructure/config/WebConfig.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/infrastructure/kafka/KafkaTopic.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/infrastructure/kafka/PaymentEventConsumer.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/infrastructure/kafka/ReservationEventProducer.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/presentation/controller/ReservationController.java
  reservation-service/src/main/resources/application.yml
  review-service/src/main/java/com/carenest/business/reviewservice/application/service/ReviewService.java
  review-service/src/main/java/com/carenest/business/reviewservice/presentation/controller/ReviewController.java
Labels: feat📌

#94 Feature/ai translate
  ai-service/build.gradle
  ai-service/src/main/java/com/carenest/business/aiservice/application/service/ReviewTranslationService.java
  ai-service/src/main/java/com/carenest/business/aiservice/infrastructure/client/GeminiClient.java
  ai-service/src/main/java/com/carenest/business/aiservice/presentation/controller/ReviewTranslationController.java
  ai-service/src/main/resources/application.properties
  ai-service/src/main/resources/application.yml
Labels: feat📌

#97 Feature/payment/toss
  payment-service/build.gradle
  payment-service/src/main/java/com/carenest/business/paymentservice/application/dto/response/PaymentHistoryDetailResponse.java
  payment-service/src/main/java/com/carenest/business/paymentservice/application/dto/response/PaymentHistoryResponse.java
  payment-service/src/main/java/com/carenest/business/paymentservice/application/dto/response/PaymentListResponse.java
  payment-service/src/main/java/com/carenest/business/paymentservice/application/dto/response/PaymentResponse.java
  payment-service/src/main/java/com/carenest/business/paymentservice/application/service/PaymentServiceImpl.java
  payment-service/src/main/java/com/carenest/business/paymentservice/domain/model/Payment.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/client/PaymentGatewayClient.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/client/ReservationInternalClient.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/client/UserInternalClient.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/client/dto/request/PaySoCancelRequestDto.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/client/dto/request/PaySoPrepareRequestDto.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/client/dto/response/PaySoApprovalResponseDto.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/client/dto/response/ReservationDetailsResponseDto.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/client/dto/response/UserInfoResponseDTO.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/config/FeignClientConfig.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/config/RestTemplateConfig.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/config/TossPaymentsConfig.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/external/PaymentGatewayServiceImpl.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/external/TossPaymentGatewayServiceImpl.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/external/toss/TossPaymentsClient.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/external/toss/dto/request/TossCancelPaymentRequest.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/external/toss/dto/request/TossPaymentConfirmRequest.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/external/toss/dto/request/TossPaymentRequest.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/external/toss/dto/response/CardResponse.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/external/toss/dto/response/CashReceiptResponse.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/external/toss/dto/response/DiscountResponse.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/external/toss/dto/response/EasyPayResponse.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/external/toss/dto/response/GiftCertificateResponse.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/external/toss/dto/response/MobilePhoneResponse.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/external/toss/dto/response/TossFailCallbackResponse.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/external/toss/dto/response/TossPaymentResponse.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/external/toss/dto/response/TossSuccessCallbackResponse.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/external/toss/dto/response/TransferResponse.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/external/toss/dto/response/UrlResponse.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/external/toss/dto/response/VirtualAccountResponse.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/repository/PaymentRepository.java
  payment-service/src/main/java/com/carenest/business/paymentservice/presentation/controller/PaymentController.java
  payment-service/src/main/java/com/carenest/business/paymentservice/presentation/controller/TossPaymentController.java
  payment-service/src/main/resources/application.yml
  reservation-service/src/main/java/com/carenest/business/reservationservice/presentation/controller/ReservationInternalController.java
  reservation-service/src/main/resources/application.yml
  user-service/src/main/java/com/carenest/business/userservice/application/service/UserService.java
  user-service/src/main/java/com/carenest/business/userservice/presentation/controller/UserInternalController.java
Labels: feat📌, refactor ⚙

#95 Feature/caregiver/kafka
  caregiver-service/build.gradle
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/service/CaregiverConsumerService.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/service/CaregiverConsumerServiceImpl.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/service/CaregiverServiceImpl.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/config/ConsumerKafkaConfig.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/domain/service/CaregiverDomainService.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/domain/service/CaregiverDomainServiceImpl.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/infrastructure/kafka/CaregiverRatingConsumer.java
  common/src/main/java/com/carenest/business/common/event/caregiver/CaregiverRatingMessage.java
  docker-compose.yml
  review-service/src/main/java/com/carenest/business/reviewservice/application/service/ReviewService.java
  review-service/src/main/java/com/carenest/business/reviewservice/config/KafkaConfig.java
  review-service/src/main/java/com/carenest/business/reviewservice/infrastructure/kafka/CaregiverRatingProducer.java
  review-service/src/main/java/com/carenest/business/reviewservice/infrastructure/kafka/KafkaTopic.java
Labels: feat📌, refactor ⚙

#99 Feature/notification service refactor
  notification-service/src/main/java/com/carenest/business/notificationservice/application/dto/kafka/PaymentCompletedEvent.java
  notification-service/src/main/java/com/carenest/business/notificationservice/application/dto/kafka/ReservationCreatedEvent.java
  notification-service/src/main/java/com/carenest/business/notificationservice/domain/model/NotificationType.java
  notification-service/src/main/java/com/carenest/business/notificationservice/infrastructure/config/KafkaConfig.java
  notification-service/src/main/java/com/carenest/business/notificationservice/infrastructure/kafka/NotificationConsumer.java
  notification-service/src/main/resources/application.yml
Labels: feat📌

#101 Feature/ai translate
  ai-service/src/main/java/com/carenest/business/aiservice/exception/AiException.java
  ai-service/src/main/java/com/carenest/business/aiservice/exception/ErrorCode.java
  ai-service/src/main/java/com/carenest/business/aiservice/exception/GlobalExceptionHandler.java
  ai-service/src/main/java/com/carenest/business/aiservice/infrastructure/client/GeminiClient.java
  ai-service/src/main/java/com/carenest/business/aiservice/presentation/controller/ReviewTranslationController.java
Labels: refactor ⚙

#105 Feature/caregiver/top10
  caregiver-service/build.gradle
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/dto/response/BulkCaregiverTop10Response.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/dto/response/CaregiverGetTop10ResponseServiceDTO.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/service/CaregiverService.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/service/CaregiverServiceImpl.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/config/CacheConfig.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/config/RedisConfig.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/presentation/controller/CaregiverController.java
Labels: feat📌, refactor ⚙

#103 Feature/#93 user errorcode
  gateway-service/build.gradle
  gateway-service/src/main/java/com/carenest/business/gatewayservice/JwtAuthFilter.java
  gateway-service/src/main/java/com/carenest/business/gatewayservice/TokenBlacklistService.java
  user-service/build.gradle
  user-service/src/main/java/com/carenest/business/userservice/UserServiceApplication.java
  user-service/src/main/java/com/carenest/business/userservice/application/service/UserService.java
  user-service/src/main/java/com/carenest/business/userservice/domain/exception/UserErrorCode.java
  user-service/src/main/java/com/carenest/business/userservice/infrastructure/security/JwtUtil.java
  user-service/src/main/java/com/carenest/business/userservice/infrastructure/security/TokenBlacklistService.java
  user-service/src/main/java/com/carenest/business/userservice/presentation/controller/UserController.java
Labels: feat📌

#110 Feature/caregiver/delete
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/service/CaregiverService.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/service/CaregiverServiceImpl.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/infrastructure/repository/CaregiverRepository.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/presentation/controller/CaregiverController.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/presentation/controller/CaregiverInternalController.java
Labels: refactor ⚙

#113 Feature/notification read filter
  common/src/main/java/com/carenest/business/common/response/ResponseDto.java
  notification-service/src/main/java/com/carenest/business/notificationservice/application/dto/request/NotificationCreateRequestDto.java
  notification-service/src/main/java/com/carenest/business/notificationservice/application/dto/response/NotificationResponseDto.java
  notification-service/src/main/java/com/carenest/business/notificationservice/application/dto/response/UserInfoResponseDto.java
  notification-service/src/main/java/com/carenest/business/notificationservice/application/service/NotificationService.java
  notification-service/src/main/java/com/carenest/business/notificationservice/application/service/NotificationServiceImpl.java
  notification-service/src/main/java/com/carenest/business/notificationservice/domain/model/Notification.java
  notification-service/src/main/java/com/carenest/business/notificationservice/domain/model/NotificationType.java
  notification-service/src/main/java/com/carenest/business/notificationservice/domain/repository/NotificationRepository.java
  notification-service/src/main/java/com/carenest/business/notificationservice/infrastructure/config/MessageConfig.java
  notification-service/src/main/java/com/carenest/business/notificationservice/infrastructure/util/AuthValidationUtil.java
  notification-service/src/main/java/com/carenest/business/notificationservice/presentation/controller/NotificationController.java
  notification-service/src/main/resources/application.yml
  notification-service/src/main/resources/messages.properties
Labels: feat📌, refactor ⚙

#116 Feature/reservation/kafka
  notification-service/src/main/java/com/carenest/business/notificationservice/application/service/NotificationServiceImpl.java
  notification-service/src/main/java/com/carenest/business/notificationservice/infrastructure/config/NotificationWebSocketHandler.java
  notification-service/src/main/java/com/carenest/business/notificationservice/infrastructure/kafka/NotificationConsumer.java
  payment-service/src/main/java/com/carenest/business/paymentservice/application/service/PaymentServiceImpl.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/application/service/ReservationServiceImpl.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/infrastructure/kafka/ReservationEventProducer.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/presentation/controller/ReservationInternalController.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/presentation/dto/request/ReservationAcceptRequest.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/presentation/dto/request/ReservationRejectRequest.java
Labels: fix 🛠, refactor ⚙

#115 Feature/admin init
  admin-service/build.gradle
  admin-service/src/main/java/com/carenest/business/adminservice/AdminServiceApplication.java
  admin-service/src/main/java/com/carenest/business/adminservice/application/dto/request/SettlementRequestDto.java
  admin-service/src/main/java/com/carenest/business/adminservice/application/dto/response/SettlementResponseDto.java
  admin-service/src/main/java/com/carenest/business/adminservice/application/service/SettlementService.java
  admin-service/src/main/java/com/carenest/business/adminservice/config/KafkaConsumerConfig.java
  admin-service/src/main/java/com/carenest/business/adminservice/config/KafkaProducerConfig.java
  admin-service/src/main/java/com/carenest/business/adminservice/domain/model/Settlement.java
  admin-service/src/main/java/com/carenest/business/adminservice/domain/model/SettlementStatus.java
  admin-service/src/main/java/com/carenest/business/adminservice/infrastructure/dto/SettlementCreatedEventDto.java
  admin-service/src/main/java/com/carenest/business/adminservice/infrastructure/kafka/NotificationKafkaProducer.java
  admin-service/src/main/java/com/carenest/business/adminservice/infrastructure/kafka/SettlementKafkaConsumer.java
  admin-service/src/main/java/com/carenest/business/adminservice/infrastructure/kafka/SettlementKafkaProducer.java
  admin-service/src/main/java/com/carenest/business/adminservice/infrastructure/repository/SettlementRepository.java
  admin-service/src/main/java/com/carenest/business/adminservice/presentation/SettlementMapper.java
  admin-service/src/main/java/com/carenest/business/adminservice/presentation/controller/SettlementController.java
  admin-service/src/main/resources/application.yml
  common/src/main/java/com/carenest/business/common/event/admin/SettlementCreatedEvent.java
  gateway-service/src/main/java/com/carenest/business/gatewayservice/GatewayConfig.java
  notification-service/src/main/java/com/carenest/business/notificationservice/infrastructure/kafka/NotificationConsumer.java
  settings.gradle
Labels: feat📌

#118 Feature/caregiver/accept
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/service/CaregiverApprovalService.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/service/CaregiverApprovalServiceImpl.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/service/CaregiverConsumerService.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/service/CaregiverConsumerServiceImpl.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/config/ConsumerKafkaConfig.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/config/FeignConfig.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/config/FeignErrorDecoderConfig.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/domain/model/CaregiverApproval.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/exception/ErrorCode.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/infrastructure/client/ReservationClient.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/infrastructure/client/dto/reservation/Gender.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/infrastructure/client/dto/reservation/PaymentStatus.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/infrastructure/client/dto/reservation/ReservationResponse.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/infrastructure/client/dto/reservation/ReservationStatus.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/infrastructure/client/dto/reservation/ServiceType.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/infrastructure/kafka/CaregiverConsumer.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/infrastructure/kafka/CaregiverRatingConsumer.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/infrastructure/repository/CaregiverApprovalRepository.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/presentation/controller/CaregiverApprovalController.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/presentation/dto/response/PendingApprovalResponse.java
  common/src/main/java/com/carenest/business/common/event/caregiver/CaregiverPendingEvent.java
  common/src/main/java/com/carenest/business/common/event/caregiver/CaregiverRatingEvent.java
  gateway-service/src/main/java/com/carenest/business/gatewayservice/GatewayConfig.java
  payment-service/src/main/java/com/carenest/business/paymentservice/application/service/PaymentServiceImpl.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/config/KafkaConfig.java
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/kafka/PaymentEventProducer.java
  review-service/src/main/java/com/carenest/business/reviewservice/infrastructure/kafka/CaregiverRatingProducer.java
Labels: feat📌

#120 refactor: 알림 조회 API를 토큰 기반으로 변경
  notification-service/src/main/java/com/carenest/business/notificationservice/presentation/controller/NotificationController.java
Labels: refactor ⚙

#122 Feature/Ai - Review FeignClient
  ai-service/src/main/java/com/carenest/business/aiservice/AiServiceApplication.java
  ai-service/src/main/java/com/carenest/business/aiservice/application/dto/ReviewResponseDto.java
  ai-service/src/main/java/com/carenest/business/aiservice/application/service/ReviewTranslationService.java
  ai-service/src/main/java/com/carenest/business/aiservice/exception/ErrorCode.java
  ai-service/src/main/java/com/carenest/business/aiservice/exception/GlobalExceptionHandler.java
  ai-service/src/main/java/com/carenest/business/aiservice/infrastructure/client/ReviewInternalClient.java
  ai-service/src/main/java/com/carenest/business/aiservice/presentation/controller/ReviewTranslationController.java
Labels: feat📌

#130 Feature/#128 gateway
  gateway-service/src/main/java/com/carenest/business/gatewayservice/application/service/TokenBlacklistService.java
  gateway-service/src/main/java/com/carenest/business/gatewayservice/infrasturcture/config/GatewayConfig.java
  gateway-service/src/main/java/com/carenest/business/gatewayservice/infrasturcture/security/JwtAuthFilter.java
  gateway-service/src/main/java/com/carenest/business/gatewayservice/infrasturcture/security/JwtUtil.java
  gateway-service/src/main/java/com/carenest/business/gatewayservice/infrasturcture/security/LoggingFilter.java
Labels: feat📌, refactor ⚙

#126 Feature/ai caregiver recommend
  ai-service/src/main/java/com/carenest/business/aiservice/application/dto/CaregiverRecommendRequestDto.java
  ai-service/src/main/java/com/carenest/business/aiservice/application/dto/CaregiverSearchConditionRequestDto.java
  ai-service/src/main/java/com/carenest/business/aiservice/application/service/CaregiverRecommendationService.java
  ai-service/src/main/java/com/carenest/business/aiservice/infrastructure/client/CaregiverInternalClient.java
  ai-service/src/main/java/com/carenest/business/aiservice/infrastructure/client/GeminiClient.java
  ai-service/src/main/java/com/carenest/business/aiservice/presentation/controller/CaregiverRecommendationController.java
Labels: feat📌

#132 feat: admin 가입 기능 추가
  user-service/src/main/java/com/carenest/business/userservice/application/dto/request/SignupRequestDTO.java
  user-service/src/main/java/com/carenest/business/userservice/application/service/UserService.java
Labels: feat📌

#135 Feature/admin settlement kafka
  admin-service/src/main/java/com/carenest/business/adminservice/AdminServiceApplication.java
  admin-service/src/main/java/com/carenest/business/adminservice/application/dto/response/PaymentListResponse.java
  admin-service/src/main/java/com/carenest/business/adminservice/application/service/SettlementService.java
  admin-service/src/main/java/com/carenest/business/adminservice/config/WebConfig.java
  admin-service/src/main/java/com/carenest/business/adminservice/exception/SettlementAccessDeniedException.java
  admin-service/src/main/java/com/carenest/business/adminservice/exception/SettlementExceptionHandler.java
  admin-service/src/main/java/com/carenest/business/adminservice/infrastructure/client/PaymentClient.java
  admin-service/src/main/java/com/carenest/business/adminservice/infrastructure/kafka/SettlementKafkaProducer.java
  admin-service/src/main/java/com/carenest/business/adminservice/presentation/controller/SettlementController.java
  admin-service/src/main/resources/application.yml
  common/src/main/java/com/carenest/business/common/exception/GlobalExceptionHandler.java
  notification-service/src/main/java/com/carenest/business/notificationservice/application/service/NotificationServiceImpl.java
  notification-service/src/main/java/com/carenest/business/notificationservice/infrastructure/kafka/NotificationConsumer.java
Labels: feat📌

#129 Feature/caregiver/check
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/service/CaregiverApprovalService.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/application/service/CaregiverApprovalServiceImpl.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/domain/model/Caregiver.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/domain/model/CaregiverStatus.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/infrastructure/client/ReservationClient.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/infrastructure/client/dto/reservation/ReservationAcceptRequest.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/infrastructure/client/dto/reservation/ReservationRejectRequest.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/infrastructure/repository/CaregiverApprovalRepository.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/infrastructure/repository/querydsl/CaregiverRepositoryImpl.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/presentation/controller/CaregiverApprovalController.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/presentation/controller/ReservationInternalController.java
Labels: feat📌, refactor ⚙

#140 Feature/docker compose
  Dockerfile
  config-service/Dockerfile
  docker-compose.yml
Labels: chore 🧲

#145 Feature/caregiver/swagger
  caregiver-service/build.gradle
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/config/SwaggerConfig.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/presentation/controller/CaregiverApprovalController.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/presentation/controller/CaregiverController.java
  caregiver-service/src/main/java/com/carenest/business/caregiverservice/presentation/controller/CaregiverInternalController.java
  gateway-service/build.gradle
  gateway-service/src/main/java/com/carenest/business/gatewayservice/infrasturcture/security/JwtAuthFilter.java
  gateway-service/src/main/resources/application.yml
Labels: docs 🗒️

#144 Feature/payment/swagger
  gateway-service/src/main/java/com/carenest/business/gatewayservice/infrasturcture/security/JwtAuthFilter.java
  gateway-service/src/main/resources/application.yml
  payment-service/build.gradle
  payment-service/src/main/java/com/carenest/business/paymentservice/infrastructure/config/SwaggerConfig.java
  payment-service/src/main/java/com/carenest/business/paymentservice/presentation/controller/PaymentController.java
  payment-service/src/main/java/com/carenest/business/paymentservice/presentation/controller/TossPaymentController.java
  payment-service/src/main/resources/application.yml
  reservation-service/build.gradle
  reservation-service/src/main/java/com/carenest/business/reservationservice/infrastructure/config/SwaggerConfig.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/presentation/controller/ReservationController.java
  reservation-service/src/main/java/com/carenest/business/reservationservice/presentation/controller/ReservationInternalController.java
  reservation-service/src/main/resources/application.yml
Labels: docs 🗒️

#147 feat: 스웨거 어노테이션 추가
  user-service/build.gradle
  user-service/src/main/java/com/carenest/business/userservice/presentation/controller/UserController.java
Labels: docs 🗒️
